import type { RequestResult } from './types'

const data: RequestResult = {
  name: 'LeoKu',
  login: 'Codennnn',
  avatarUrl:
    'https://avatars.githubusercontent.com/u/47730755?u=b42b926a9de7d3d3161a9ddf9ba9e67fb74ee6b3&v=4',
  contributionsCollection: { years: [2022, 2021, 2020, 2019] },
  contributionCalendars: [
    {
      total: 589,
      weeks: [
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'THIRD_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FOURTH_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'THIRD_QUARTILE', weekday: 1 },
            { level: 'THIRD_QUARTILE', weekday: 2 },
            { level: 'FOURTH_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'THIRD_QUARTILE', weekday: 5 },
            { level: 'THIRD_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'THIRD_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FOURTH_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'THIRD_QUARTILE', weekday: 2 },
            { level: 'THIRD_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'FOURTH_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'THIRD_QUARTILE', weekday: 4 },
            { level: 'FOURTH_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FOURTH_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'THIRD_QUARTILE', weekday: 4 },
            { level: 'THIRD_QUARTILE', weekday: 5 },
            { level: 'THIRD_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'THIRD_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'THIRD_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'FOURTH_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'THIRD_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'THIRD_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'THIRD_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'FOURTH_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'THIRD_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'FOURTH_QUARTILE', weekday: 1 },
            { level: 'THIRD_QUARTILE', weekday: 2 },
            { level: 'THIRD_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FOURTH_QUARTILE', weekday: 5 },
            { level: 'FOURTH_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FOURTH_QUARTILE', weekday: 0 },
            { level: 'THIRD_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        { days: [{ level: 'NONE', weekday: 0 }] },
      ],
      year: 2022,
    },
    {
      total: 474,
      weeks: [
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'THIRD_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FOURTH_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FOURTH_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FOURTH_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'FOURTH_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'THIRD_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'FOURTH_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'FOURTH_QUARTILE', weekday: 1 },
            { level: 'FOURTH_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'THIRD_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'THIRD_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'THIRD_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FOURTH_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
      ],
      year: 2021,
    },
    {
      total: 1809,
      weeks: [
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'THIRD_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'FOURTH_QUARTILE', weekday: 2 },
            { level: 'THIRD_QUARTILE', weekday: 3 },
            { level: 'THIRD_QUARTILE', weekday: 4 },
            { level: 'FOURTH_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'THIRD_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FOURTH_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'THIRD_QUARTILE', weekday: 3 },
            { level: 'FOURTH_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'FOURTH_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'THIRD_QUARTILE', weekday: 0 },
            { level: 'FOURTH_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'THIRD_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'THIRD_QUARTILE', weekday: 5 },
            { level: 'FOURTH_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FOURTH_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'FOURTH_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'FOURTH_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'THIRD_QUARTILE', weekday: 0 },
            { level: 'THIRD_QUARTILE', weekday: 1 },
            { level: 'THIRD_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'THIRD_QUARTILE', weekday: 5 },
            { level: 'THIRD_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'THIRD_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'THIRD_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
          ],
        },
      ],
      year: 2020,
    },
    {
      total: 3031,
      weeks: [
        {
          days: [
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'THIRD_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'NONE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'NONE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'THIRD_QUARTILE', weekday: 1 },
            { level: 'FOURTH_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'THIRD_QUARTILE', weekday: 3 },
            { level: 'FOURTH_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'FOURTH_QUARTILE', weekday: 4 },
            { level: 'FOURTH_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FOURTH_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FOURTH_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'FOURTH_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'FOURTH_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'THIRD_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'SECOND_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'THIRD_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FOURTH_QUARTILE', weekday: 0 },
            { level: 'FOURTH_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'NONE', weekday: 3 },
            { level: 'THIRD_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'FOURTH_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'THIRD_QUARTILE', weekday: 0 },
            { level: 'THIRD_QUARTILE', weekday: 1 },
            { level: 'FOURTH_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'THIRD_QUARTILE', weekday: 5 },
            { level: 'SECOND_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'THIRD_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'THIRD_QUARTILE', weekday: 2 },
            { level: 'THIRD_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'FIRST_QUARTILE', weekday: 5 },
            { level: 'NONE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'NONE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'NONE', weekday: 2 },
            { level: 'THIRD_QUARTILE', weekday: 3 },
            { level: 'FOURTH_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'THIRD_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'FIRST_QUARTILE', weekday: 1 },
            { level: 'FIRST_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'FIRST_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'THIRD_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'FIRST_QUARTILE', weekday: 0 },
            { level: 'NONE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
            { level: 'SECOND_QUARTILE', weekday: 4 },
            { level: 'SECOND_QUARTILE', weekday: 5 },
            { level: 'FIRST_QUARTILE', weekday: 6 },
          ],
        },
        {
          days: [
            { level: 'SECOND_QUARTILE', weekday: 0 },
            { level: 'SECOND_QUARTILE', weekday: 1 },
            { level: 'SECOND_QUARTILE', weekday: 2 },
            { level: 'FIRST_QUARTILE', weekday: 3 },
          ],
        },
      ],
      year: 2019,
    },
  ],
}

export default data
